Initial commit. Add set and get methods for applicable attributes.
umple/umple pull request #1007
Opened 2017-02-27 06:32 UTC by katcavers

## Description

This PR is the first step in bringing generated API methods to the model level for issue #962 . This commit includes changes to add a get and set method for applicable attributes at the model level. Currently, these additional methods are skipped over in the code generation stage, so generation of API methods remains unchanged.

I tried to find all the generators and add the necessary code to skip generation of the get and set methods. If any were missed, please let me know.

## Tests

Added a test in UmpleParserTest called autoGeneratedAPIMethods.

2017-02-27 18:20 UTC, vahdat-ab commented
@katcavers The build is failing. Please fix them and request your PR again.

2017-02-27 22:23 UTC, katcavers commented
@vahdat-ab It is fixed now. I had forgotten to commit one file, oops!

2017-02-28 16:15 UTC, vahdat-ab requested changes

2017-02-28 16:15 UTC, vahdat-ab commented on cruise.umple/test/cruise/umple/compiler/UmpleParserTest.java
> +  public void autoGeneratedAPIMethods()
It is better to keep test cases simple.  Each test case should be dealing with a specific case. It helps later to explore the test case easier.  One test case for every stereotype. You can keep the source model the same for all test cases.

2017-02-28 18:19 UTC, vahdat-ab commented
Great. 
You also need to take care of errors like 1009. The way they have been implemented must be changed because now we have auto-generated methods at the model.
you can get more details about errors related to attributes in `en.error`.
you can create another issue for the metioned case and I'll merge this PR, or you can update the PR and then I'll merge. I prefer the second one :-)

2017-03-02 00:37 UTC, katcavers commented on cruise.umple/test/cruise/umple/compiler/UmpleParserTest.java
> +  public void autoGeneratedAPIMethods()
Is there a way to only have to call assertSimpleParse once if I separate them all into separate tests? Or do I have to call it now for each test?

2017-03-02 03:25 UTC, vahdat-ab commented
@katcavers the build is failing

2017-03-02 05:59 UTC, katcavers commented
@vahdat-ab yes, I know, I didn't mean to push the last commit. I commented on your code review, but perhaps you didn't see it? Just in case, here is the question again:
Is there a way to only have to call assertSimpleParse once if I separate them all into separate tests? Or do I have to call it now for each test?
Thanks!

2017-03-02 15:15 UTC, vahdat-ab commented
Yes, you can do it inside `public void setUp()`. However, I would suggest breaking your file to several files in the direct connection with the tests you do. In that case, you parse things (use assertSimpleParse ) related to each test case.

2017-03-02 16:57 UTC, katcavers commented
Okay, so should I (1) keep the tests where they are in UmpleParserTest and create separate .ump files to parse for each test case, or (2) create a new test file for these tests and use the setup method to parse the .ump file once, or (3) create a new test file for these tests and use separate .ump files for each of them?

Which would be best? :)

2017-03-02 19:58 UTC, vahdat-ab commented
Option 1

2017-03-03 18:37 UTC, vahdat-ab commented on cruise.umple/src/Generator_CodeGvClassDiagram.ump
> +
I wonder why you wanted to escape these methods here?
Actually, it's a nice way to show what them in the model. By default, we don't shows any methods, but when they are selected they should be shown

2017-03-03 18:41 UTC, vahdat-ab commented
@TimLethbridge I wonder if you wanted to have Umple auto-generated methods to appear in generators like Json, scxml, etc. To me, it makes sense to have them there as well.

2017-03-12 15:28 UTC, vahdat-ab commented on cruise.umple/src/Generator_CodeGvClassDiagram.ump
> +
as we discussed online, disregard my point.

2017-03-12 15:30 UTC, vahdat-ab commented
I wonder if you have done sth related to this PR or not? If no, so I want to merge this.
Probably you can add remove methods to this PR so they are all merged together.

2017-03-12 19:30 UTC, katcavers commented
Hey Vahdat, yes I had thought that after our meeting a week ago it was going to be pulled. But you are right, adding the remove methods to this PR makes sense. Hopefully I have that ready to go by the end of today.

2017-03-14 03:33 UTC, katcavers commented
Hi Vahdat, I saw one of the checks failed, and looked in the logs to find this:
    [junit] Running cruise.statemachine.test.DoActivityTest
    [junit] Tests run: 8, Failures: 0, Errors: 1, Time elapsed: 36.028 sec

I believe this is why it failed? How can I debug the problem? All tests passed locally

2017-03-15 04:54 UTC, katcavers commented
I'm also really confused as to why this commit could cause this to start failing...the only difference is a new test and two methods which are actually never called anywhere in the code yet. The previous commit passed both travis-ci builds.

2017-03-15 21:54 UTC, vahdat-ab commented
That's ok. The test fails because of pool/queue state machines. This is a random failure.

2017-03-15 22:57 UTC, vahdat-ab reviewed
I have a question:
do yo deal with constructor at the modeling level or not?
if yes then when an attribute is removed its constructor needs to be modified.

2017-03-15 22:57 UTC, vahdat-ab commented on cruise.umple/src/Umple_Code.ump
> +  	ArrayList<Method> methodsCopy = new ArrayList<Method>(this.getMethods());
It is better to define the variable more general.
`List<Method> methodsCopy = new ArrayList<Method>(this.getMethods());`

2017-03-16 05:10 UTC, katcavers commented
Yes, I am working on the constructor now. I am almost done, but I had not considered this. I will look into it tomorrow. Thank you!

2017-03-16 18:24 UTC, katcavers commented on cruise.umple/src/Umple_Code.ump
> +  	ArrayList<Method> methodsCopy = new ArrayList<Method>(this.getMethods());
Okay I will make this change.

2017-03-22 03:56 UTC, merged