Revised externalexamples/readme.txt for clairity and conciseness.
umple/umple pull request #1016
Opened 2017-03-15 19:01 UTC by anTrodaire

As part of a technical writing course, we were asked to improve
documentation on GitHub. I've revised externalexamples/readme.txt so it
reads better.

2017-03-15 19:36 UTC, vahdat-ab requested changes

2017-03-15 19:36 UTC, vahdat-ab commented on externalexamples/readme.txt
> +We invite people to create their own umple exaples, including proper test cases.
Please consider the following cases,
- Umple should be started always with an uppercase letter `U`
- There is a typo in your modification  -> `exaples`

2017-03-15 19:37 UTC, vahdat-ab commented
when you do PR, please make sure it points at the issue you created. Therefore, once the PR is merged, teh issue will be closed.

2017-03-15 20:45 UTC, anTrodaire commented on externalexamples/readme.txt
> +We invite people to create their own umple exaples, including proper test cases.
Sorry about that! Fixed.

2017-03-16 13:56 UTC, vahdat-ab commented
Thank you for the PR 👍

2017-03-16 13:56 UTC, merged