Resolve issue 1008
umple/umple pull request #1047
Opened 2017-04-22 23:40 UTC by jblang94

# Description
This PR addresses issue #1008. Umple now supports enumerations. A user can define an enumeration within a class, or at the top-most level of an Umple model. Enumerations defined at the top-most level of an Umple model are shared by classes. The `enumerationDefinition` rule is defined in "umple_classes.grammar". A new `UmpleEnumeration` type has been created as well. All code for handling enumerations in UmpleInternalParser is in  "UmpleInternalParser_CodeEnumeration.ump".

The Umple User Manual now has a section for "Enumerations". Documentation for errors and warnings related to enumerations have also been added to the user manual.

## New Errors and Warnings
- E095 Duplicate Enumerations
- E096 Enumeration and Class Name Conflict
- E097 Enumeration and State Machine Conflict
- W098 Enumeration Causes Attribute Ambiguity
- W102 Enumeration Causes Method Parameter Ambiguity
- W103 Enumeration Causes Event Parameter Ambiguity
- E104 Enumeration in Bi-directional Association
- E105 Enumeration in Composition
- W106 Enumeration in Uni-directional Association

## New Tests
### UmpleParserTest
- parseUmpleEnumerationDefinedInClass
- parseUmpleEnumerationDefinedAtTopLevel
- parseUmpleEnumerationDefinedAtTopLevelAndInClass
- namingConflictBetweenEnumerationAndClass
- enumerationConflictsWithStateMachine
- attributeAmbiguityCausedByEnumeration
- methodParameterAmbiguityCausedByEnumeration
- eventParameterAmbiguityCausedByEnumeration
- enumerationInBidirectionalAssoc
- enumerationInComposition
- enumerationInUnidirectionalAssoc
### JavaClassTemplateTest
- TestUmpleEnumerations_*

2017-04-27 17:08 UTC, vahdat-ab commented
@jblang94 Thanks for the PR. Check my comments.

2017-04-27 17:08 UTC, vahdat-ab commented
@TimLethbridge This PR has some material written for the user manual. It needs your review.

2017-04-27 17:18 UTC, TimLethbridge commented
I am fine with the manual entries

2017-04-27 21:58 UTC, jblang94 commented
@vahdat-ab thanks! I don't see your other comments other than the one in which you asked Tim to review the manual entries.
@TimLethbridge thanks for reviewing

2017-04-27 22:00 UTC, vahdat-ab requested changes

2017-04-27 22:00 UTC, vahdat-ab commented on umpleonline/ump/manualexamples/E104EnumerationInBidirectionalAssociation2.ump
> +// attribute of type "Y".
The error should be because of not having a unique name for the enumeration.  If an enumeration is created at the modeling level, its name must be unique.

2017-04-27 22:00 UTC, vahdat-ab commented on umpleonline/ump/manualexamples/E105EnumerationInComposition2.ump
> +enum Y { Red, Blue, Green }
The error should be because of not having a unique name for the enumeration. If an enumeration is created at the modeling level, its name must be unique.

2017-04-27 22:00 UTC, vahdat-ab commented on umpleonline/ump/manualexamples/W098EnumerationCausesAttributeAmbiguity1.ump
> +// be an object of class "Y" or the enumeration "Y"
The error should be because of not having a unique name for the enumeration. If an enumeration is created at the modeling level, its name must be unique

2017-04-27 22:00 UTC, vahdat-ab commented on umpleonline/ump/manualexamples/W102EnumerationCausesMethodParameterAmbiguity1.ump
> +enum Y { Red, Blue, Green }
The error should be because of not having a unique name for the enumeration. If an enumeration is created at the modeling level, its name must be unique

2017-04-27 22:00 UTC, vahdat-ab commented on umpleonline/ump/manualexamples/W103EnumerationCausesEventParameterAmbiguity2.ump
> +
The error should be because of not having a unique name for the enumeration. If an enumeration is created at the modeling level, its name must be unique

2017-04-27 22:00 UTC, vahdat-ab commented on umpleonline/ump/manualexamples/W106EnumerationInUnidirectionalAssociation3.ump
> +
The error should be because of not having a unique name for the enumeration. If an enumeration is created at the modeling level, its name must be unique

2017-04-27 22:01 UTC, vahdat-ab commented
I put notes on files. Can you see now?

2017-04-27 22:27 UTC, vahdat-ab commented
Please make sure line number in errors and warnings are correct. They all the time show `1`.

2017-04-28 18:11 UTC, jblang94 commented
@vahdat-ab I've addressed all of your comments except the line number issue. 

When enumerations are defined in classes, I've found that the position is correct, however, for model-level enumerations, the line number is always set to 1. I've dug around in the parsing code, and have seen in the `init(Position usePosition)` method in `ParserDataPackage.java` that it calculates the correct number of lines in the Umple file. I found that the `findPosition` method in `Terminal.java` sets the position of tokens in the Umple file. However it uses `keys` to calculate the line number, and as a result of the logic, it is always setting the line number of model-level enumerations to 1. Before I continue diagnosing the issue, I'm wondering if I should keep poking around here, or if you have any suggestions for where I should be looking? I am also wondering if maybe I forgot to add something to the parsing rules? For your reference
```
// Defined enumeration in umple_classes.grammar
enumerationDefinition : enum [name] { [enumValue](, [enumValue])* }

// | [[enumerationDefinition]] onto classContent in umple_classes.grammar

// | [[enumerationDefinition]] onto entity in umple_core.grammar

```

2017-04-29 05:48 UTC, vahdat-ab commented
could you please commit that fix about having unique names for enumerations, classes, traits, and interfaces. I could make an example to test position. Once you're done with that. I'll check again the position case.

2017-04-29 17:22 UTC, jblang94 commented
@vahdat-ab just pushed all of my current changes

2017-04-30 23:36 UTC, vahdat-ab commented
Thanks.

2017-04-30 23:44 UTC, merged