Fixes issue 1026
umple/umple pull request #1083
Opened 2017-09-19 23:54 UTC by AlexJoshuaMcManus

The equals() and hash() functions for keys within a class now exclusively call get methods
This prevents the issue of trying to access private inherited members directly while also keeping a consistent format

https://github.com/umple/umple/issues/1026

**IMPORTANT**: By submitting a patch, you agree that your work will be licensed under the [license](https://github.com/umple/umple/blob/master/LICENSE.md) used by the project.

If your pull request does not pass CI, it will **not** be merged (unless *heavily* justified). 

## Description

Applies a fix to issue 1026

## Tests

Had to change existing tests since they were expecting java code to be produced which directly accesses member variables (we now only call the gettters). All other tests passed and those that were modified now pass as well.

Closes #1026

2017-09-21 02:45 UTC, TimLethbridge requested changes
THis PR needs one or two additional tests for the code that resulted in the issue to start with. In other words there should be a test for code
```
class Test{
  id;
}

class Sub{
  isA Test;
  key {id}
}
```
demonstrating that it parses and/or generates correct output.

2017-09-23 14:56 UTC, AlexJoshuaMcManus commented
I have added some testbed tests to test the generated java output to verify that it is syntactically correct. I have also added a fix to issue 1089 because it was discovered while writing some of the tests and was blocking the completion of this task.

2017-09-24 13:21 UTC, vahdat-ab commented
@TimLethbridge  I think there might be some cache issue with Travis for the PR. I could do a full build without failure on my machine and Joshua did as well. I think we had such an issue before as well.

2017-09-24 13:54 UTC, Nava2 commented
@vahdat-ab I blew out the relevant cache and re-ran the build, best of luck. 👍

2017-09-24 15:54 UTC, vahdat-ab commented
@Nava2 Thanks. Looks like it didn't resolve the issue :-(

2017-09-25 12:35 UTC, TimLethbridge commented
I am going to test it on my machine. If it works there too, it might be something to do with the version of the java compiler still being cached. I have seen these PR builds fail on Travis before, then succeed after the merge. Stand by.

2017-09-25 12:45 UTC, TimLethbridge commented
OK So this PR fails the following:

AssociationEndTest	equals_checkAllData_nullNowSameAsEmpty	Failure	expected:<true> but was:<false>

junit.framework.AssertionFailedError: expected:<true> but was:<false>
at cruise.umple.compiler.AssociationEndTest.equals_checkAllData_nullNowSameAsEmpty(AssociationEndTest.java:292)

It needs updating and testing again before merging @AlexJoshuaMcManus

2017-09-25 14:15 UTC, TimLethbridge commented
It might be that this fails after merging due to some subtlety; perhaps the wrong files end up being present after the merge. When I went to test it, it said that master had diverged. It prompted me twice to merge. I believe my results are the same as the results that Travis is getting. It is not clear why others don't see the same failed tests. Are you searching through the logs of the full build to look for failed tests? Are you looking at the generated QA page?

2017-09-25 16:16 UTC, AlexJoshuaMcManus commented
I'll try looking into it more, but I have looked through the full build output as well as the QA page and neither mention any failed tests. @vahdat-ab was also getting the same failed tests, but he did a fresh clone of the repository and saw all tests pass. Did you clone a new version of the repository, or just pull in my branch, @TimLethbridge? 

I have already done a fresh clone of the repository and tested it with success. What I think I'll do if I can't identify the issues is just create a new PR with a new branch and copy over my changes. I'm suspecting that this is because I didn't rebase before committing the first time.

2017-09-25 16:29 UTC, Nava2 commented
Have you tried manually merging (or rebasing) master into your branch? As a temporary test, try that and see if there's any issues. Re-doing your changes doesn't help find the issue.

2017-09-25 16:32 UTC, AlexJoshuaMcManus commented
Yes I have rebased with master and committed the update. I will try doing it again (since master has been updated since I last did my rebase) when I have the time and update you on the results. Thanks for the help.

2017-09-26 18:12 UTC, vahdat-ab commented
Just a report:
1) I did make a fresh repository and didn't build it.
2) run the following commands as Github recommended.
```
git fetch origin
git checkout -b fix-1026_jmcmanus origin/fix-1026_jmcmanus
git merge master
```

3) I did a first build.
4) I did a full build.
5) It passes all test cases. I run this on Windows.

2017-09-26 21:18 UTC, TimLethbridge commented
OK following these instructions results in a pass on my machine. so I am going to risk it and merge. I think the mixup with wrong editing of history during the sprint caused some issues. Let's hope this works.

2017-09-26 21:18 UTC, merged

2017-09-26 22:18 UTC, AlexJoshuaMcManus commented
Okay, thank you for the update. Please let me know if you see any abnormalities and I'll return to this issue and investigate it further.