Fixes #893 Add visit counter for Umple Online
umple/umple pull request #1390
Opened 2018-10-14 03:57 UTC by glorialaw

**IMPORTANT**: By submitting a patch, you agree that your work will be licensed under the [license](https://github.com/umple/umple/blob/master/LICENSE.md) used by the project.

If your pull request does not pass CI, it will **not** be merged (unless *heavily* justified). Before submitting, do a git pull to bring in other changes from master; then also do a full build and verify that the words 'error' or 'failure' do not appear anywhere in the build transcript (don't rely on BUILD SUCCESSFUL appearing). The 'bumple' script in dev-tools can help with this.

PRs should always be made from a branch you have created on umple/umple, not from a fork: This ensures that a Docker image of your PR can be automatically generated for manual testing.

## Pull request title

In the title, include a 3-10 word summary of what improvements the PR makes.

If the PR fixes one or more issues, the title must have the format "Fixes #ISSUE_NUM1[, #ISSUE_NUM2...] summary ..." This will automatically close the issue when the PR is merged. If the PR partially fixes an issue, but not completely, say "Progress on #ISSUE_NUM  summary".

If your PR only updates .txt files that are not used in the build, then you can tell Travis and Appeyor to not build by including [ci skip] in the title.

## Pull request description

Visit counter is added on the bottom right hand corner.

## Pull request content

Include automated tests for  every change to the compiler and all other parts of the system where automated tests are possible. 

Add updates to the user manual in build/reference if you are making changes to syntax and semantics

Verify you have included all needed files and have not included extraneous changed files. Make each PR as small (agile) as possible.

After you have submitted a PR, watch the Travis and Appveyor. If the build fails on these CI servers, you can push additional changes to the branch associated with the PR to update it.

2018-10-14 10:08 UTC, TimLethbridge reviewed
Note that I edited the pull request comment! You had left the template comment (I had to do this for your last pull request too).

2018-10-14 10:08 UTC, TimLethbridge commented on umpleonline/umple.php
> +	<div class="visitors-count" align="right">
Although this seems to work, any div should be inside the body tag, so the end body tag just above needs to be below the end of this div

2018-10-14 21:27 UTC, glorialaw commented
I have fixed the umple.php and PR comment. Thanks for letting me know @TimLethbridge

2018-10-15 00:25 UTC, TimLethbridge requested changes
I just realized one more thing: countlog.txt can't be in version control. Why not? It will get reset every time umpleonline is updated. Simply delete the file; in your checks for its readability, simply create it with a value of 1 if it does not exist. Also put countlog.txt in .gitignore so its creation and changes don't trigger git to suggest it as a changed file.

2018-10-15 01:29 UTC, glorialaw commented
The changes have been made

2018-10-15 09:40 UTC, TimLethbridge commented
This latest change doesn't seem to work. When trying it in docker, the counter doesn't update (but error messages are turned off)

So I tried this in my own local UmpleOnline, which should be the same as on the production server. My first result was: 
```
Warning: fopen(/Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/countlog.txt): failed to open stream: Permission denied in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 13

Warning: fwrite() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 14

Warning: fclose() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 15

Warning: chmod(): No such file or directory in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 18

Warning: fopen(/Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/countlog.txt): failed to open stream: No such file or directory in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 20

Warning: fgets() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 21

Warning: fclose() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 22
1 visits since October 2018
Warning: fopen(/Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/countlog.txt): failed to open stream: Permission denied in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 28

Warning: fwrite() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 29

Warning: fclose() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 30
```

Then I created the file manually and I got:
```
Warning: chmod(): Operation not permitted in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 18
1 visits since October 2018
Warning: fopen(/Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/countlog.txt): failed to open stream: Permission denied in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 28

Warning: fwrite() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 29

Warning: fclose() expects parameter 1 to be resource, boolean given in /Users/tcl/Documents/7--Research/2-CRuiSE/codebase/googleumple/umple/umpleonline/counter.php on line 30
```

So the user has to manually create the file. I think the only way forward is to simply check for file existence and do nothing if the file is absent. Please make a change to that effect.

By the way, I pushed a change to .gitignore so when the .txt file is changed it does not get tracked as a change.

2018-10-15 23:50 UTC, glorialaw commented
Thanks for letting me know! I have made the made the changes.

I tested the file adding part by deleting the countlog.txt file on my computer and those errors did not occur. However, when I first used the code from the website, I got those errors due to the incorrect file permissions on my system for the countlog.txt file.

2018-10-16 06:02 UTC, TimLethbridge approved these changes

2018-10-16 06:02 UTC, merged