Issue2023curlybracket
umple/umple pull request #2049
Opened 2023-11-01 17:37 UTC by AxelTWC

Pull Request for #2023 
## Issue2023curlybracket

This code currently raises a warning and detects the following Extra Brackets:

- OPEN_ROUND_BRACKETS
- CLOSE_ROUND_BRACKETS
- OPEN_CURLY_BRACKETS
- CLOSE_CURLY_BRACKETS 

and outputs the warning number 1016. 

In order to remove the warning, the user would need to look at the warning message showing the line number of the extra bracket.

## Note
- For Developers, Quick Build the Compiler twice as there is an edit in the Umple Internal Parser Code.
- Multiple Test Cases has been added to test and solve this issue. 
- An extra user manual guideline has been added to show how to reproduce this warning and how to solve the warning.

2023-11-13 23:22 UTC, AxelTWC commented
## Reasons for commits:

## Test Cases accidentally all have Class instead of class.
An example would be:
- Class x{}
It was changed to:
- class x{}

## Jenkins Giving Failed Warnings.
- It does not pass Jenkins as Jenkins only build the compiler once
- Since there is a change in the internal parser code, the compiler should be compiled twice in order for brackets to be detected.

2023-11-13 23:55 UTC, TimLethbridge requested changes

2023-11-13 23:55 UTC, TimLethbridge commented on cruise.umple/src/class/umple_classes.grammar
> +openCurlBracket- : {
Please remove these two unneeded rules

2023-11-13 23:55 UTC, TimLethbridge commented on cruise.umple/src/class/UmpleInternalParser_CodeClass.ump
> +    //System.out.print("Token:" + t);
Please take out this debug code

2023-11-13 23:55 UTC, TimLethbridge commented on cruise.umple/src/class/UmpleInternalParser_CodeClass.ump
> +    //Reveals the current detected class token
Please take out this debug code

2023-11-13 23:55 UTC, TimLethbridge commented on cruise.umple/src/class/UmpleInternalParser_CodeClass.ump
> +    else if (token.is("checkForUnintendedBracket")){
This check should only be at the top level ... and hence should only be there once ...

2023-11-13 23:55 UTC, TimLethbridge commented on cruise.umple/src/class/umple_classes.grammar
> +// Associations can be declared outside the body of classes.
Please reset so there is no change to the space here

2023-11-13 23:55 UTC, TimLethbridge commented on cruise.umple/src/class/umple_classes.grammar
> +classContent- :  [[comment]] | [[reqImplementation]] | [[innerClass]] | [[mixsetDefinition]] | [[distributable]] | [[proxyPattern]] | [[strictness]] | [[classDefinition]] | [[trace]] | [[emitMethod]]
Please reset so there is no change to the line ... it is just a space

2023-11-13 23:55 UTC, TimLethbridge commented on cruise.umple/src/en.error
> +1020: 3, "http://manual.umple.org/?PageBeingDeveloped.html", Extra closing curly bracket encountered. Processing terminated. All code beyond this point is ignored. ;
Please take out 1020 and change 1016 so the 'Processing terminated and following is no longer there.

2023-11-14 18:15 UTC, TimLethbridge approved these changes

2023-11-14 18:16 UTC, merged