Adding color to state diagrams.
umple/umple pull request #2058
Opened 2023-11-17 15:34 UTC by syedahmed1674

## PR TITLE
Adding color to state diagram 
## PR description

The way color can be added to state diagrams is by typing the keyword displayColor (or displayColour) and then followed by the colour or an = then colour name. Example displayColor red

2023-11-17 15:38 UTC, AxelTWC commented on cruise.umple/src/generators/statemachineDiagramGenerator/Generator_CodeGvStateDiagram.ump
> +
Remove extra space

2023-11-17 15:40 UTC, AxelTWC commented on cruise.umple/src/generators/statemachineDiagramGenerator/Generator_CodeGvStateDiagram.ump
> +
my bad. not needed

2023-11-17 17:04 UTC, TimLethbridge commented
My first observation is that the following code properly colours the leaf states, but not the outer ones.

```
class X {
  sm {
    outerS1 {
      displayColor beige;
      s11 {
        displayColour green;
        e1 -> outerS2;
        e2 -> s12;
        e3 -> s22;
      }
      s12 {
        e4 -> s22;
        displayColour blue;
      }
    }
    outerS2 {
      displayColour yellow;
      e3 -> s12;
      s21 {
        displayColor #AAEECC;
      }
      s22 {
        e1 -> outerS1;
      }
    }
  }
}
```

2023-11-17 17:27 UTC, TimLethbridge requested changes
You need to add tests, and to ensure that outer states in nested state diagrams can also be coloured.

2023-11-17 17:27 UTC, TimLethbridge commented on cruise.umple/src/generators/statemachineDiagramGenerator/Generator_CodeGvStateDiagram.ump
> +        // Retrieve the display color of an object 's'
Comment should say 'of the state, rather than of an object'

2023-11-23 14:54 UTC, TimLethbridge approved these changes

2023-11-23 15:05 UTC, merged