Support the implementation of "color"
umple/umple pull request #2060
Opened 2023-11-22 19:11 UTC by AxelTWC

## PR Title
Support the implementation of Display Color assignment with Parenthesis within the value.
# Example
displayColor = "red"
## PR Description
It was originally stated by @syedahmed1674 that by implementing the following into UmpleInternaalParser_CodeLayout + _CodeClass:
```
theColor = theColor.replace("=", ""); // Remove all '=' characters
theColor = theColor.replace(""", ""); // Remove all '"' characters
```
It would fix the issue by replacing any parsed values for the Coloring to remove the assignment sign and the quotation sign, It was later found that it does not pass through Grammar Test Cases and raises error 1502. 

It was later discovered by @AxelTWC debugging that by removing the code:
```
      if(!theColor.startsWith("\"")) theColor= "\""+theColor;
      if(!theColor.endsWith("\"")) theColor= theColor+"\"";
``` 

It solves the issue where there will not be an extra " whenever having a quotation valued assignment 
(Originally Debugging Gives " "red" by doing displayColor = "red" | It should fix the issue now)

@syedahmed1674 Will Push Test Cases Specifically for this PR /Issue #2056

2023-11-22 19:17 UTC, AxelTWC commented
Be reminded that there are no Test Cases yet as I am unsure if it being modifying the parser code will have an affect on test cases.
Previously Mentioned for #2023.
However, @syedahmed1674 will push the test cases and he will follow up on this issue.

2023-11-24 13:56 UTC, AxelTWC commented
Test Cases has been done by @syedahmed1674 and should correctly solve the issue #2056

2023-11-27 19:09 UTC, TimLethbridge requested changes

2023-11-27 19:09 UTC, TimLethbridge commented on cruise.umple/src/class/UmpleInternalParser_CodeClass.ump
> -        if(!theColor.startsWith("\"")) theColor= "\""+theColor;
This PR does not yet solve all cases.

Specifically

```
class X {
  displayColor = "#dfdfdf";
  a;
}
```

(not the space after the equals sign. My suggestion, yes, remove any equals sign. Remove any quotes wherever they are; then use the trim() function to remove spaces before adding the needed quotes.

2023-11-27 22:40 UTC, TimLethbridge approved these changes

2023-11-27 22:57 UTC, merged